// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duinqqwpytebfqsueofk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1aW5xcXdweXRlYmZxc3Vlb2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzODI1MTAsImV4cCI6MjA2NDk1ODUxMH0.Cseb1RNouSZhkgiCs6jzU1h7hsLL6OeGWnEEO8vIiXo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);